apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: epub-reader
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
images:
- name: epub-reader
  newName: ghcr.io/jungting20/epub-anki-web-app
  digest: sha256:4ac60075f8ed8f310b4a02ac52ec74e48c55c2c6a0718f1a9fcb60c0af384db5
